### ISSUE TITLE
Pipe symbol causes failures

### ISSUE THREAD

**Issue by toddbruner** [lkundrak/perl-WWW-Splunk#1]
The Query:

sourcetype="tcp-raw" minutesago=15 NOT "gov" NOT "arpa" NOT "localhost" NOT "loopback" uri_domain="*" | stats count(uri_domain) by uri_domain

works from splunk web page, but fails when I use it with WWW::Splunk.  If I truncate from the pipe sybmol on, I get results.  I really wish to use the splunk aggregation function though.

Splunk REST API seems to indicate this is possible in python.  Could this be an encoding problem in the libwww stuff used to send the query to the splunk server?

Thanks,
Todd

**Comment by lkundrak** [comment]
I believe this is fixed now. Can you confirm please and eventually reopen if it still does not work for you?
